brand:
  title: 品牌提升
  content: 为相关纺织行业供应链企业打造个性化PC官网，移动APP应用，微信公众号，微信小程序及微商城，提升企业形象，开拓线上销售渠道，提高品牌效应。

search:
  title: 搜索平台
  content: 为毛绒行业提供人工智能图像识别搜索撮合平台，宗旨在帮助毛绒工厂或经销商企业，实现库存查询、库存变现、新品推广，拓展销售渠道，降低开发成本和周期，帮助毛绒采购方降低采购成本，提高效率。

aierp:
  title: 行业AIERP
  content: 人工智能和大数据赋予企业ERP不仅是管理上的可视化还会将数据进行计算与分析，将会更加结果化，以更易理解和直观的内容展示给公司管理层决策者。

resource:
  title: 资源对接
  content: 找个样小程序为纺织行业资源共享对接平台，为面料需求提供找料更方便、找料更全面、找料成本低，为供应拓展客户群，获得精准顾客，促进产品销售。

aiemployee:
  title: AI员工
  content: 让人工智能员工更加专业化更科学化更加理性化为客户服务，做到智能推荐，高效向导。

